version: '3'

services:
  # Soft
  vsftpd:
    image: jshotyk/ftp.base:latest
    container_name: ftp.base
    ports:
      - 2121:21
    environment:
      - FTP_USER=ftpuser
      - FTP_PASS=supersecret 
      - FTP_HOME=default
      - FTP_UID=1000
      - ONLY_UPLOAD=NO
      - ONLY_DOWNLOAD=NO
      - PASV_ENABLE=NO
      - PASV_ADDRESS=yourserveradress.com
      - PASV_MIN=21100
      - UMASK=022
  ndpi:
    build: 
      context: ./home/user/projects/Docker/nDPI
      dockerfile: Dockerfile
    image: jshotyk/ndpi-base:latest 
    container_name: ndpi-base
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./ndpi_config:/usr/local/etc/ndpi
      - ./pcap:/pcap
    network_mode: "host"